In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.3.0'

### For the Hello World example, Let ys try the equation y = 3x+3

In [3]:
xs = np.array([-1.0,0.0,1.0,2.0,3.0,4.0],dtype = float)
ys = np.array([-1.0,2.0,5.0,8.0,11.0,14.0],dtype = float)

In [4]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(units = 1,input_shape = [1]))
model.add(Dense(units = 10))
model.add(Dense(units = 1))

In [10]:
model.compile(optimizer = 'sgd',loss = 'mean_squared_error')

In [11]:
model.fit(xs,ys,epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 76.3275
Epoch 2/100
1/1 [==============================] - 0s 996us/step - loss: 60.0593
Epoch 3/100
1/1 [==============================] - 0s 998us/step - loss: 49.6273
Epoch 4/100
1/1 [==============================] - 0s 716us/step - loss: 32.5794
Epoch 5/100
1/1 [==============================] - 0s 995us/step - loss: 8.9860
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7104
Epoch 7/100
1/1 [==============================] - 0s 931us/step - loss: 0.5367
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3756
Epoch 9/100
1/1 [==============================] - 0s 997us/step - loss: 0.2863
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2138
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1648
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1263
Epoch 13/100
1/1 [===========================

1/1 [==============================] - 0s 101us/step - loss: 7.6890e-11
Epoch 100/100
1/1 [==============================] - 0s 253us/step - loss: 6.1507e-11


In [12]:
# y = 3x+2
model.predict([10])

array([[31.999975]], dtype=float32)

In [20]:
model.predict([96,20])

array([[289.99966],
       [ 61.99994]], dtype=float32)

In [21]:
model.summary()    # params 2,10,11 are input is 1, dense is 1 so 1*1 + 1 bias, so params = 2
                   # 'lly, input is 1,dense is 10 so 1*10 = 10 , bias +10 so params = 20 
                   # 'lly, input is 1,dense is 1, so 1*1 = 1,bias +11 so params = 11

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [28]:
from tensorflow.keras.utils import plot_model
plot_model(model,'model.png',show_shapes = True)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [30]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.1615857]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.20518], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(1, 10) dtype=float32, numpy=
 array([[-0.11142282, -0.19928212,  0.12910819,  0.48615575,  0.9411589 ,
         -1.0004151 , -0.1764926 ,  0.539199  ,  0.02975615, -0.05879268]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=
 array([ 0.10641939,  0.06769024,  0.08668615,  0.22478907,  0.24821207,
        -0.23601379,  0.21775301,  0.23801354, -0.18341033,  0.10630061],
       dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(10, 1) dtype=float32, numpy=
 array([[ 0.20772968],
        [ 0.07871678],
        [ 0.26066935],
        [ 0.7389124 ],
        [ 0.984101  ],
        [-0.97962576],
        [ 0.4464735 ],
        [ 0.79254943],
        [-0.42551732],
        [ 0.22933835]], dtype=float32)>,
 <tf.V